# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Sergei Surovtsev
title: Hobo Programmer
email: cyberwizard.ru@gmail.com

# Social links
github_username:  cwiz

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Learning new stuff.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
